version = 0.1

[default.deploy.parameters]
stack_name       = "worker-app-stack"
region           = "us-east-2"
confirm_changeset = true
capabilities     = "CAPABILITY_IAM"
disable_rollback = false
resolve_s3       = true
s3_prefix        = "worker-app-stack"
image_repositories = []
parameter_overrides = "ExistingUserPoolId=\"us-east-2_3hnWNGVkJ\" ExistingUserPoolClientId=\"52r7dt137d6vj2h4ch49t8krrs\""

